import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const sampleArticles = [
  // 日本
  {
    title: "花王ロリエ、肌に優しい新素材ナプキンを発売",
    summary: "花王は、敏感肌にも安心な新素材を採用したロリエブランドの生理用ナプキンを発表しました。天然コットン100%の表面シートが特徴です。",
    content: "花王株式会社は本日、ロリエブランドから肌に優しい新素材を採用した生理用ナプキンの新ラインを発表しました。天然コットン100%の表面シートを採用し、敏感肌の方でも安心して使用できる設計となっています。吸収力も従来品比120%に向上しており、日中の長時間使用にも対応します。",
    url: "https://www.kao.co.jp/laurier/",
    imageUrl: null,
    country: "JP",
    brand: "ロリエ",
    company: "花王",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-08"),
  },
  {
    title: "ユニ・チャーム ソフィ、超薄型ナプキンで快適性を追求",
    summary: "ソフィから厚さわずか2mmの超薄型ナプキンが登場。スリムながら高い吸収力を実現し、アクティブな女性に人気です。",
    content: "ユニ・チャームは、ソフィブランドから超薄型の生理用ナプキンを新発売しました。わずか2mmの薄さながら、独自の吸収体により従来品と同等の吸収力を実現。運動時でもフィット感が持続する設計で、アクティブな女性をサポートします。",
    url: "https://www.unicharm.co.jp/ja/brands/sofy.html",
    imageUrl: null,
    country: "JP",
    brand: "ソフィ",
    company: "ユニ・チャーム",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-07"),
  },
  {
    title: "Nagi、サステナブルな吸水ショーツの新コレクション発表",
    summary: "日本発の吸水ショーツブランドNagiが、リサイクル素材を使用した環境配慮型の新コレクションを発表しました。",
    content: "吸水ショーツブランドNagiは、リサイクルポリエステルを使用した新コレクション「Re:Nagi」を発表しました。使用済みペットボトルから作られた繊維を採用し、環境への配慮と快適な着用感を両立しています。吸収量は約40mlで、普通の日なら1枚で安心して過ごせます。",
    url: "https://nfrm.jp/nagi/",
    imageUrl: null,
    country: "JP",
    brand: "Nagi",
    company: "BLAST Inc.",
    category: "underwear",
    source: "scraping",
    publishedAt: new Date("2026-02-06"),
  },
  {
    title: "大王製紙エリス、夜用ナプキンの吸収力が大幅アップ",
    summary: "エリスの夜用ナプキンがリニューアル。従来比150%の吸収力で朝まで安心の睡眠をサポートします。",
    content: "大王製紙は、エリスブランドの夜用生理用ナプキンをリニューアルしました。独自の3層吸収構造により、従来品比150%の吸収力を実現。40cmのロングサイズで後ろ漏れもしっかりガードし、朝まで安心して眠れます。",
    url: "https://www.elleair.jp/elis/",
    imageUrl: null,
    country: "JP",
    brand: "エリス",
    company: "大王製紙",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-05"),
  },
  {
    title: "Bé-A Japan、スポーツ向け吸水ショーツを展開",
    summary: "Bé-A Japanがスポーツシーンに特化した吸水ショーツを発売。ヨガやランニングでも快適に過ごせる設計です。",
    content: "Bé-A Japanは、スポーツ向けの吸水ショーツ「Bé-A Sport」を発売しました。通気性の高い素材と伸縮性に優れた設計で、ヨガやランニング、ジムでのトレーニング中でも快適に過ごせます。吸収量は約30mlで、軽い日のスポーツシーンに最適です。",
    url: "https://bea-japan.com/",
    imageUrl: null,
    country: "JP",
    brand: "Bé-A",
    company: "Bé-A Japan",
    category: "underwear",
    source: "scraping",
    publishedAt: new Date("2026-02-04"),
  },
  // アメリカ
  {
    title: "Always Infinity FlexFoam introduces biodegradable options",
    summary: "P&G's Always brand launches eco-friendly biodegradable pads under the Infinity FlexFoam line, responding to consumer demand for sustainable menstrual products.",
    content: "Procter & Gamble has introduced a new biodegradable option within its popular Always Infinity FlexFoam line. The new pads use plant-based materials that decompose within 12 months in commercial composting facilities. This move responds to growing consumer demand for environmentally sustainable menstrual products.",
    url: "https://always.com/",
    imageUrl: null,
    country: "US",
    brand: "Always",
    company: "P&G",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-08"),
  },
  {
    title: "Thinx launches next-gen period underwear with improved absorption",
    summary: "Thinx unveils its latest period underwear collection featuring 50% more absorption capacity and a sleeker design for all-day comfort.",
    content: "Thinx Inc. has announced the launch of its next-generation period underwear collection. The new line features a proprietary four-layer technology that provides 50% more absorption compared to previous models. Available in multiple styles from bikini to high-waist, the collection is designed for maximum comfort throughout the day.",
    url: "https://www.thinx.com/",
    imageUrl: null,
    country: "US",
    brand: "Thinx",
    company: "Thinx Inc.",
    category: "underwear",
    source: "scraping",
    publishedAt: new Date("2026-02-07"),
  },
  {
    title: "Kotex introduces teen-friendly menstrual pad range",
    summary: "Kimberly-Clark's Kotex brand launches a specially designed pad range for teenagers, featuring smaller sizes and fun packaging.",
    content: "Kimberly-Clark has launched U by Kotex Teen, a line of menstrual pads specifically designed for teenagers experiencing their first periods. The range features smaller sizes appropriate for younger bodies, educational packaging with helpful information, and a more discrete design for school use.",
    url: "https://www.ubykotex.com/",
    imageUrl: null,
    country: "US",
    brand: "Kotex",
    company: "Kimberly-Clark",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-06"),
  },
  // イギリス
  {
    title: "Bodyform launches period poverty initiative across UK",
    summary: "Essity's Bodyform brand partners with UK schools to provide free menstrual products and education programs to combat period poverty.",
    content: "Bodyform, owned by Essity, has announced a major initiative to combat period poverty across the United Kingdom. The program will provide free menstrual products to over 1,000 schools and educational institutions, along with comprehensive menstrual health education materials.",
    url: "https://www.bodyform.co.uk/",
    imageUrl: null,
    country: "GB",
    brand: "Bodyform",
    company: "Essity",
    category: "general",
    source: "scraping",
    publishedAt: new Date("2026-02-08"),
  },
  {
    title: "WUKA period underwear sees 200% growth in UK market",
    summary: "British brand WUKA reports record sales growth as UK consumers increasingly adopt reusable period underwear for sustainable menstruation.",
    content: "WUKA, a UK-based period underwear brand, has reported a 200% year-over-year growth in sales. The company attributes this success to growing consumer awareness of sustainable menstrual products and the cost-effectiveness of reusable period underwear compared to disposable products over time.",
    url: "https://www.wuka.co.uk/",
    imageUrl: null,
    country: "GB",
    brand: "WUKA",
    company: "WUKA Ltd",
    category: "underwear",
    source: "scraping",
    publishedAt: new Date("2026-02-07"),
  },
  // フランス
  {
    title: "Nana France lance une gamme de protections bio certifiées",
    summary: "Essityのフランスブランド「Nana」がオーガニック認証取得の生理用ナプキンを発売。フランス国内のオーガニック需要に対応。",
    content: "Essity傘下のフランスブランドNanaが、EU認証のオーガニックコットンを使用した生理用ナプキンの新ラインを発表しました。フランスでは近年、生理用品のオーガニック志向が強まっており、この製品は無漂白・無香料で肌への優しさを追求しています。",
    url: "https://www.nfrm.fr/nana/",
    imageUrl: null,
    country: "FR",
    brand: "Nana",
    company: "Essity",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-07"),
  },
  {
    title: "フランス発Fempo、吸水ショーツのサブスクリプションサービスを開始",
    summary: "パリ発の吸水ショーツブランドFempoが月額制のサブスクリプションモデルを導入。定期的に新しいショーツが届くサービスです。",
    content: "フランスのパリを拠点とする吸水ショーツブランドFempoが、業界初となる月額制サブスクリプションサービスを開始しました。月額19.90ユーロで毎月1枚の吸水ショーツが届き、3ヶ月ごとに古くなったショーツの回収・リサイクルも行います。",
    url: "https://ffrm.fr/fempo/",
    imageUrl: null,
    country: "FR",
    brand: "Fempo",
    company: "Fempo SAS",
    category: "underwear",
    source: "scraping",
    publishedAt: new Date("2026-02-06"),
  },
  // ドイツ
  {
    title: "ドイツで生理用品の付加価値税撤廃後、売上が30%増加",
    summary: "ドイツでの生理用品に対する付加価値税撤廃政策の効果が明らかに。消費者の購買行動に大きな変化が見られています。",
    content: "ドイツ連邦統計局の最新データによると、生理用品に対する付加価値税の引き下げ以降、市場全体の売上が30%増加しました。特に高品質なオーガニック製品や吸水ショーツなどの付加価値の高い製品カテゴリでの成長が顕著です。",
    url: "https://www.destatis.de/",
    imageUrl: null,
    country: "DE",
    brand: null,
    company: null,
    category: "general",
    source: "newsapi",
    publishedAt: new Date("2026-02-08"),
  },
  // スウェーデン
  {
    title: "Libresse Sweden introduces carbon-neutral menstrual pad line",
    summary: "EssityのスウェーデンブランドLibresseがカーボンニュートラルな生理用ナプキンを発表。北欧のサステナビリティ基準をリードします。",
    content: "Essity傘下のLibresseブランドが、製造から廃棄までのカーボンフットプリントを完全にオフセットしたカーボンニュートラルな生理用ナプキンラインを発表しました。スウェーデンの厳格な環境基準に適合し、包装材にもリサイクル素材を100%使用しています。",
    url: "https://www.libresse.se/",
    imageUrl: null,
    country: "SE",
    brand: "Libresse",
    company: "Essity",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-07"),
  },
  // インド
  {
    title: "インドで低価格生理用ナプキンの普及が加速",
    summary: "インド政府の補助金プログラムにより、農村部での生理用ナプキンの普及率が過去5年で3倍に増加しました。",
    content: "インド政府が推進する「Suvidha」プログラムにより、1枚あたり1ルピー（約1.5円）の低価格ナプキンの供給が加速しています。農村部での普及率は過去5年間で3倍に増加し、女性の健康改善と教育参加率の向上に貢献しています。",
    url: "https://www.whisper.in/",
    imageUrl: null,
    country: "IN",
    brand: "Whisper",
    company: "P&G",
    category: "pad",
    source: "newsapi",
    publishedAt: new Date("2026-02-08"),
  },
  {
    title: "インド発Carmesi、プレミアム吸水ショーツでアジア市場へ進出",
    summary: "インドの生理用品ブランドCarmesiが、プレミアムラインの吸水ショーツでアジア太平洋地域への展開を発表。",
    content: "ムンバイを拠点とするCarmesiが、プレミアム吸水ショーツラインを発表し、東南アジアおよび日本市場への進出計画を明らかにしました。インドの伝統的なテキスタイル技術を活かした独自の吸収素材が特徴です。",
    url: "https://mycarmesi.com/",
    imageUrl: null,
    country: "IN",
    brand: "Carmesi",
    company: "Carmesi",
    category: "underwear",
    source: "newsapi",
    publishedAt: new Date("2026-02-06"),
  },
  // 韓国
  {
    title: "韓国Yejimiin、K-ビューティー発想の生理用ナプキンが話題",
    summary: "韓国のYejimiinが美容成分を配合した生理用ナプキンを発売。スキンケア発想のアプローチが若い世代に人気です。",
    content: "韓国の生理用品ブランドYejimiinが、ヒアルロン酸やシカ成分を配合した生理用ナプキンを発売しました。K-ビューティーのスキンケア発想を生理用品に取り入れたこの製品は、デリケートゾーンの肌ケアを同時に行える点が20〜30代の女性に支持されています。",
    url: "https://www.yuhan-kimberly.co.kr/",
    imageUrl: null,
    country: "KR",
    brand: "Yejimiin",
    company: "Yuhan-Kimberly",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-07"),
  },
  {
    title: "韓国発Jiyoun、テクノロジー搭載スマート吸水ショーツを開発中",
    summary: "韓国のスタートアップJiyounが、経血量をトラッキングできるスマート吸水ショーツのプロトタイプを発表。",
    content: "ソウルのフェムテックスタートアップJiyounが、内蔵センサーにより経血量をスマートフォンアプリで記録できる吸水ショーツのプロトタイプを発表しました。月経周期の管理に役立つデータをリアルタイムで提供し、婦人科受診時の参考情報としても活用できます。",
    url: "https://www.jiyountech.com/",
    imageUrl: null,
    country: "KR",
    brand: "Jiyoun",
    company: "Jiyoun Tech",
    category: "underwear",
    source: "newsapi",
    publishedAt: new Date("2026-02-05"),
  },
  // オーストラリア
  {
    title: "Modibodi、世界初の海洋プラスチック再生吸水ショーツを発表",
    summary: "オーストラリアのModibodiが、海洋プラスチックをリサイクルした素材で作られた吸水ショーツを世界初発売。",
    content: "オーストラリアの吸水ショーツブランドModibodiが、海洋から回収されたプラスチックをリサイクルした繊維で製造した吸水ショーツコレクションを発表しました。1枚のショーツ製造に約5本分のペットボトル相当のリサイクル素材を使用しています。",
    url: "https://www.modibodi.com/",
    imageUrl: null,
    country: "AU",
    brand: "Modibodi",
    company: "Modibodi",
    category: "underwear",
    source: "scraping",
    publishedAt: new Date("2026-02-08"),
  },
  // カナダ
  {
    title: "カナダ政府、全公共施設での無料生理用品提供を義務化",
    summary: "カナダ連邦政府が全国の公共施設における無料生理用品の設置を義務化する法案を可決しました。",
    content: "カナダ連邦議会は、全国の公共施設（学校、図書館、政府機関など）における無料生理用品の設置を義務化する法案を可決しました。これにより、カナダは世界でも最も包括的な生理用品アクセス政策を持つ国の一つとなります。",
    url: "https://www.canada.ca/en/health-canada.html",
    imageUrl: null,
    country: "CA",
    brand: null,
    company: null,
    category: "general",
    source: "newsapi",
    publishedAt: new Date("2026-02-07"),
  },
  {
    title: "Stayfreeがカナダ市場向けオーガニック製品ラインを投入",
    summary: "J&JのStayfreeブランドがカナダのオーガニック需要に応え、認証オーガニックコットン使用のナプキンラインを発売。",
    content: "Johnson & Johnsonは、Stayfreeブランドからカナダ市場向けにオーガニック認証コットンを使用した生理用ナプキンの新ラインを発売しました。カナダの消費者の環境意識の高まりに対応した製品で、包装材もすべて再生可能素材を使用しています。",
    url: "https://www.stayfree.com/",
    imageUrl: null,
    country: "CA",
    brand: "Stayfree",
    company: "Johnson & Johnson",
    category: "pad",
    source: "scraping",
    publishedAt: new Date("2026-02-06"),
  },
];

async function seed() {
  console.log("=== サンプルデータ投入開始 ===");

  for (const article of sampleArticles) {
    try {
      await prisma.article.upsert({
        where: { url: article.url },
        update: {
          title: article.title,
          summary: article.summary,
          content: article.content,
          imageUrl: article.imageUrl,
          country: article.country,
          brand: article.brand,
          company: article.company,
          category: article.category,
          source: article.source,
          publishedAt: article.publishedAt,
        },
        create: article,
      });
      console.log(`  ✓ ${article.title.substring(0, 40)}...`);
    } catch (error) {
      console.error(`  ✗ ${article.title.substring(0, 40)}:`, error);
    }
  }

  const count = await prisma.article.count();
  console.log(`\n=== 完了: ${count} 件の記事がDBに登録されています ===`);

  await prisma.$disconnect();
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
